    public void testRefArraySum()
    throws Exception {
        refArrayFunctionTest("SUM");
    }

