    // This test is written as expected-to-fail and should be rewritten
    // as expected-to-pass when the bug is fixed.
    @Test
    public void bug60158() throws IOException {
        try {
            fromFile(POIDataSamples.getDocumentInstance(), "60158.docm");
            fail("This test passes now. Please update the unit test and bug 60158.");
        } catch (ArrayIndexOutOfBoundsException e) {
            skipTest(e);
        }
    }

