    public void testLoad()
            throws Exception
    {

        TableRecord record = new TableRecord(new TestcaseRecordInputStream((short)0x236, (short)data.length, data));

        assertEquals(3, record.getRowFirst());
        assertEquals(8, record.getRowLast());
        assertEquals(4, record.getColFirst());
        assertEquals(6, record.getColLast());
        assertEquals(0, record.getFlags());
        assertEquals(4, record.getRowInputRow());
        assertEquals(1, record.getColInputRow());
        assertEquals(0x4076, record.getRowInputCol());
        assertEquals(0, record.getColInputCol());

        assertEquals( 16 + 4, record.getRecordSize() );
        record.validateSid((short)0x236);
    }

