    public void doTest() throws Exception {
        Thread t = new Thread(this, "test");
        t.start();
        t.join();
    }

