    public void testAddNew() throws Exception {
    	
    }

